### ISSUE TITLE
cannot scroll with touchpad to bottom

### ISSUE THREAD

**Issue by pyaazkaparatha** [mate-desktop/mate-control-center#306]
#### Expected behaviour
 Scrolling should go till the end

#### Actual behaviour
Scrolling doesn't goes to the end at certain sizes.

#### Steps to reproduce the behaviour

   1. open m-c-c window
  2.  reduce width of the window to 2 rows of items so that distance between the right border and second row is maximum
   3 move to slider from right vertical scrollbar to the bottom.
  4  grap the window edge on the right side and increase slowly the width of the window until the slider jumps up.
    5Try to scroll to bottom or grab the slider with mouse to bottom,......does not work.

#### MATE general version
1.19.1

#### Package version
mate-control-center-1.19.1-1.fc27.x86_64

#### Linux Distribution
Fedora 27

#### Link to downstream report of your Distribution
NA

Link for related bug in Caja
https://github.com/mate-desktop/caja/issues/755

**Comment by raveit65** [comment]
Confirmed, with using mouse in f26. I need to check it with my laptop with touchpad hardware.

**Comment by raveit65** [comment]
Issue still exists wit m-c-c-1.18.2 in f26 with using touchpad and mouse.

**Comment by monsta** [comment]
Looks like the issue that I discussed with Ubuntu MATE users:
https://ubuntu-mate.community/t/caja-window-scrolling/14861

(skip the bits about Caja, it should be fixed by now)

**Comment by tarakbumba** [comment]
I have exactly same issue on Mageia Cauldron system with m-c-c 1.19.2; using hdmi output to my Philips tv with 1280x1024 resolution (to see screen better altough tv supports hd). I can scroll m-c-c window when it is resized but not at fullscreen. Also, i can't pull scroll bar down with mouse and touchpad.

**Comment by ssspacez** [comment]
Still happening on MATE 1.20, Ubuntu MATE 18.04, I've tested today in a VM, GNOME Boxes.

It stops scrolling in the middle/half of the window.

**Comment by gstorhaug** [comment]
Still happening in the final release of Ubuntu Mate 18.04.  I am able to maximize the window to see all options though, and filtering also enables me to fine the options I need.

**Comment by tamplan** [comment]
Tested yesterday with m-c-c-1.23.f30.x86_64, the bug is unconfirmed for me, right?

**Comment by pyaazkaparatha** [comment]
the issue still occur with mate-control-center
Version      : 1.24.1
Release      : 1.fc32

**Comment by raveit65** [comment]
yes, same with f32 and 1.25/master

**Comment by rbuj** [comment]
It works fine after resizing the window.
I think something is missing... layout code at libslab/app-resizer.c

**Comment by raveit65** [comment]
yeah, point (2) from first post is important to trigger the issue.
```
2. reduce width of the window to 2 rows of items so that distance between the right border and second row is maximum
```
When reducing the space between right border and last row (rtl) than the issue is gone.

**Comment by raveit65** [comment]
New fedora downstream report.
https://bugzilla.redhat.com/show_bug.cgi?id=1872813
